component: http
name: http-express-t59QoaEMyx
inputs:
  src:
    src: ./
    exclude:
      - .env
  faas:
    framework: express
    name: '${name}'
    runtime: Nodejs12.16
    eip: false
    timeout: 3
    memorySize: 512
    tags: []
    environments: []
    layers:
      - name: '${output:${stage}:${app}:hx-antd-ui-serve-layer.name}'
        version: '${output:${stage}:${app}:hx-antd-ui-serve-layer.version}'
  apigw:
    protocols:
      - http
      - https
    timeout: 60
    environment: release
    customDomains: []
  region: ap-guangzhou
  isAutoCiDeploy: false
org: '1302167662'
app: hx-antd-ui-serve
stage: dev
